print("=" * 50)
print("        SISTEMA CENTRAL DE ARQUIVAMENTO")
print("                  VERSÃO 4.17")
print("=" * 50)
print()

operador = input("Identificação do operador: ")

while operador == "":
    print("Identificação obrigatória.")
    operador = input("Identificação do operador: ")

print()
print("Credenciais aceitas.")
print(f"Bem-vindo, {operador}.")
print()
print("Verificando registros pendentes...")
print()
print("1 arquivo associado ao operador encontrado.")
print()
print("-" * 50)
print("ARQUIVO: 017-A")
print("CLASSIFICAÇÃO: RESTRITO")
print("STATUS: INCOMPLETO")
print(f"OPERADOR ASSOCIADO: {operador}")
print("-" * 50)
print()
print("O arquivo requer revisão.")
print()
input("Pressione Enter para encerrar a sessão...")